//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_DIALOG1                     101
#define IDI_ICON1                       102
#define IDR_MENU1                       103
#define IDB_BITMAP1                     105
#define IDI_NOT                         112
#define IDI_UP                          113
#define IDI_DOWN                        114
#define IDI_LEFT                        115
#define IDI_RIGHT                       116
#define IDI_HAND2                       117
#define IDI_FOOT                        118
#define IDC_PLAY                        1000
#define IDC_STOP                        1001
#define IDC_PREV                        1002
#define IDC_NEXT                        1003
#define IDC_SLIDER1                     1004
#define IDC_PAUSE                       1005
#define IDC_COMBO1                      1006
#define IDC_POSITION                    1007
#define IDC_TITLE                       1009
#define IDC_ADDFILE                     1012
#define IDC_REMOVE                      1013
#define ID_VIEW                         1014
#define IDC_LIST2                       1015
#define IDC_SCROLLBAR1                  1017
#define IDC_LSAVE                       1018
#define IDC_LOPEN                       1019
#define IDC_LIST1                       1021
#define IDC_LIST3                       1024
#define IDC_EDIT1                       1025
#define IDC_COMBO2                      1028
#define IDC_REPOSITION                  1029
#define IDC_COMBO3                      1030
#define IDC_MADD                        1031
#define IDC_MDEL                        1032
#define IDC_MSAVE                       1033
#define IDC_MLOAD                       1034
#define IDC_LOOPPLAY                    1035
#define IDC_FDEL                        1036
#define IDC_BTUP                        1040
#define IDC_BTDOWN                      1041
#define IDC_BTLEFT                      1042
#define IDC_BTRIGHT                     1043
#define IDC_BTFOOT                      1044
#define IDC_BTHAND                      1045
#define IDC_NEWMN                       1046
#define IDC_MAKERESOURCE                1047
#define IDC_LSTDEL                      1048
#define IDC_ICON1                       1049
#define IDC_ICON2                       1050
#define IDC_ICON3                       1051
#define IDC_ICON4                       1052
#define IDC_ICON5                       1053
#define IDC_ICON6                       1054
#define IDC_ICON7                       1055
#define IDC_ICON8                       1056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
