//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDR_MENU1                       102
#define IDI_ICON1                       103
#define IDC_VIEWL1                      1000
#define IDC_VIEWL2                      1001
#define IDC_VIEWL3                      1002
#define IDC_VIEWL4                      1003
#define IDC_WORK1                       1004
#define IDC_WORK2                       1005
#define IDC_WORK3                       1006
#define IDC_WORK4                       1007
#define IDC_OBJECTCOMBO1                1008
#define IDC_VIEWL6                      1009
#define IDC_WORK5                       1010
#define IDC_VIEWL5                      1011
#define IDM_OPEN                        40001
#define IDM_SAVESPACE                   40002
#define IDM_SAVERESULT                  40003
#define IDM_EXIT                        40004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
